### ISSUE TITLE
Add new options to initialize Cartup with a specific .YAML template

### ISSUE THREAD

**Issue by mendesbarreto** [mendesbarreto/cartup#15]
Today the template copied from project comes with the two options google cloud and amazon s3 like: 
```
project:
  framework:
    version: "0.0.1"
    name: "<Name you use to archive the FRAMEWORK on Carthage>"
  google:
    project_id: "<Insert here Google project ID>"
    credentials_file: "Insert here The path to credential file that you download from firebase"
    bucket: '<Insert here the name of destination bucket on google cloud>'
  s3:
    region: "<Insert Region Name where you bucket is located"
    bucket_name: "<The nam of you bucket>"
    bucket_access_key: '<Your access key>'
    bucket_secret_key: '<Your secret key>'
```

We should add a parameter like: --s3 or --google-storage to inform cartup to only create the template wished. Like

`cartup init --s3`

output:

```
project:
  framework:
    version: "0.0.1"
    name: "<Name you use to archive the FRAMEWORK on Carthage>"
  s3:
    region: "<Insert Region Name where you bucket is located"
    bucket_name: "<The nam of you bucket>"
    bucket_access_key: '<Your access key>'
    bucket_secret_key: '<Your secret key>'
```
